# Macierze

---

Język python sam w sobie nie obsługuje działania na macierzach dlatego korzystamy ze specjalnej biblioteki numpy, której zadaniem jest przygotowanie pythona do operacji na "macierzach".

Pakiet numpy jest używany w większości analiz numerycznych w Pythonie. To pakiet zawierający wydajne środowisko do pracy nawektorach, macierzach i strukturach wielowymiarowych. Biblioteka została zaimplementowana w języku C oraz Fortranie co sprzyja szybkości działania algorytmów.

In [1]:
# stwórzmy macierz

## Po co mi macierze przecież są typy sekwencyjne ?

- Lista w Pythonie jest bardzo ogólna, może zawierać obiekty dowolnego typu, sa dynamicznie typowane
- Listy nie posiadają metod matematycznych i algebraicznych
- Macierze są jednolite
- Macierze są efektywne (szczególnie na pamięci i operacji numerycznych)
- Implementacja operacji w C i Fortranie przyspiesza pracę

## Co gdyby macierzy nie było ?

In [2]:
import numpy as np

In [3]:
sizeL = 100000
L = range(sizeL)
Lnp = np.arange(sizeL)

In [4]:
# oblicz czas obliczenia kwadratu każdej liczby

## Tworzenie macierzy

Istnieje kilka opcji na tworzenie/inicjalizowanie macierzy

In [5]:
x1d = np.array([0,1,2,3]) #1D
x2d = np.array([[0,1,2],[0,1,2]]) #2Db

In [6]:
# Najczęstszy błąd

In [7]:
type(x1d), type(x2d)

(numpy.ndarray, numpy.ndarray)

In [8]:
x1d.shape, x2d.shape # Wektor 1D a Macierz 2D

((4L,), (2L, 3L))

In [9]:
x1d.size, x2d.size

(4, 6)

In [10]:
x1d.ndim, x2d.ndim

(1, 2)

## List czy Tuple ?

In [11]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
x = np.array(((1,2,3),(4,5,6)))
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


## Funkcje tworzące macierze

In [12]:
# arange(start,end,step)

In [13]:
# linspace(start,end,number of points)

In [14]:
# ones, zeros, eye, diag, empty

## Losowe

In [15]:
print(np.random.rand(4)) # [0,1]
print(np.random.randn(4)) # Gaussian

[ 0.27211529  0.0463711   0.70005175  0.03099633]
[-1.00330215  0.96413828 -0.00494227 -0.25479982]


In [16]:
# Stwórz macierz z 10 liczbami losowymi od 0 do 66
print(np.random.rand(10)*66)

[ 38.35786521  15.9083772   38.56970238  40.25716078  63.66961794
  32.20881358  16.21819599   8.77198276  60.88480086   3.86713002]


In [17]:
np.zeros([5,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

## Typy danych wewnątrz macierzy

In [18]:
print(np.array([1,2,3]).dtype)
print(np.array([1.1,2.,3.9]).dtype)

int32
float64


In [19]:
print(np.array([1,2,3], dtype=float).dtype)

float64


In [20]:
print(np.ones(5).dtype) # Domyślny typ danych

float64


In [21]:
print(np.array([True, False, False, True]).dtype)

bool


In [22]:
# Czy w macierzy możemy przechowywać tekst ? jaki typ wewnętrzny danych uzyskamy ?

In [23]:
# co gdy wprowadzimy różne typy ?

## Indeksy i przycinanie
* Indexing and slicing (indeksowanie i krajanie na plastry(Google translate)/ziomki na plastry/plasterkowanie)

Indeksowanie i przynacie macierzy odbywa się w ten sam sposób co w przyupadku prostych typów sekwencyjnych

In [25]:
a = np.arange(10)
print(a)
print(a[0])
print(a[::-1]) # odwrotnie
print(a[2:6:2]) # od 2 do 6 ze skokiem 2

[0 1 2 3 4 5 6 7 8 9]
0
[9 8 7 6 5 4 3 2 1 0]
[2 4]


In [27]:
np.set_printoptions(precision=2)

a=np.random.rand(3,3)
print(a)
print(a[(1,1)]) # trzy sposoby
print(a[1]) # sam wiersz
print(a[:,0]) # sama kolumna

[[ 0.76  0.21  0.19]
 [ 0.47  0.34  0.52]
 [ 0.82  0.68  0.84]]
0.338898655053
[ 0.47  0.34  0.52]
[ 0.76  0.47  0.82]


![fig](http://scipy-lectures.org/_images/numpy_indexing.png)

### Zadania na indexy
* Stwórz macierz 10 na 10 w środku 0 na zewnątrz 1 (2 linijki)
* Stwórz macierz 8 na 8 wypełniając ją naprzemiennie 1 i 0 (szachownica)

## Kopie i widoki

Operacja wycinania (slicing) tworzy widok macierzy a nie nową macierz

In [33]:
a = np.ones((10,10))

print('Macierz a',a)
print('---')

b = a[1:4:2,:] # Wycinek macierzy tworzy wyłącznie widok tej macierzy, a nie nową macierz

print('Wycinek b',b)
print('---')
b[:]=12

print('Wycinek b zmodyfikowany',b)
print('---')
print('Macierz A',a)
print('---')

# Dzieje się tak tylko w przypadku widoku

('Macierz a', array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]))
---
('Wycinek b', array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]))
---
('Wycinek b zmodyfikowany', array([[ 12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.]]))
---
('Macierz A', array([[  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.

In [60]:
a = np.ones((10,10))

b = a[1:4:2,:].copy() # jeżeli nie chce tworzyć odniesienia do macierzy źródłowej używamy metody copy

print(b)
print('---')
b[:]=12

print(b)
print('---')
print(a)
print('---')

# Dzieje się tak tylko

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
---
[[ 12.  12.  12.  12.  12.  12.  12.  12.  12.  12.]
 [ 12.  12.  12.  12.  12.  12.  12.  12.  12.  12.]]
---
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
---


## Zmyślne indexowanie (fancy indexing)

In [34]:
a = np.random.randint(0, 21, 15)
print(a)
print('---')
mask = (a%3 == 0)
print(mask)
print('---')
extract_from_a = a[mask] # albo bezpośrednio a[a%3==0]
print(extract_from_a) # Zamiast indexu użylismy maski zawierającej wartości True/False

[11 14  2  9 13 14  3  0  3 19 12 11  1  4  3]
---
[False False False  True False False  True  True  True False  True False
 False False  True]
---
[ 9  3  0  3 12  3]


### Zadanie
Przypisz każdej liczbie w macierzy a większej od 10 wartość -1

In [38]:
a = np.random.randint(0, 21, 15)
print(a)
a[a>10]=-1
print(a)

[ 5 15 14  1 14  6 11 14  5  3  9  3  8  7  4]
[ 5 -1 -1  1 -1  6 -1 -1  5  3  9  3  8  7  4]


Możemy również podać zbiór "współrzędnych" elementó maceirzy tkóre chcemy wyciągnąć

![fig2](http://scipy-lectures.org/_images/numpy_fancy_indexing.png)

## Operacje na macierzach

In [41]:
a = np.array([1,2,3,4.0])
print(a)

[ 1.  2.  3.  4.]


In [40]:
print(a+2) #suma
print(a**2) #kwadrat

[ 3.  4.  5.  6.]
[  1.   4.   9.  16.]


In [43]:
a = np.array([1,2,3,4.0])
b = np.array([0.1,0.4,1,5])
np.add(a,b,out=a) # parametr out
np.negative(a,out=a)
print(a)
# add, subtract, divide, negative, multiply

[-1.1 -2.4 -4.  -9. ]


In [49]:
a = np.ones((2,3)) #dtype
b = np.random.random((2,3))
print(a)
print(b)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.71  0.86  0.83]
 [ 0.5   0.22  0.91]]


In [50]:
b+=a
print(b)

[[ 1.71  1.86  1.83]
 [ 1.5   1.22  1.91]]


In [47]:
a+=b
print(a)

[[ 1.73  1.71  1.56]
 [ 1.41  1.4   1.05]]


### Array multiplication in not matrix multiplication

In [51]:
a*b

array([[ 1.71,  1.86,  1.83],
       [ 1.5 ,  1.22,  1.91]])

In [53]:
a.dot(b.T)

array([[ 5.4 ,  4.63],
       [ 5.4 ,  4.63]])

## Funkcje

In [55]:
a = np.arange(5)
print(a)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))
print(np.abs(a))
print(np.arctan2(a,a[::-1]))

[0 1 2 3 4]
[ 0.    0.84  0.91  0.14 -0.76]
[ -inf  0.    0.69  1.1   1.39]
[  1.     2.72   7.39  20.09  54.6 ]
[0 1 2 3 4]
[ 0.    0.32  0.79  1.25  1.57]


C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


## Transpozycja, odwrotność, wyznacznik

In [65]:
a=np.random.randint(0,10,(3,3))
b = a.transpose()
b = a.T # to samo 
print(a)
print(b)

[[0 3 2]
 [9 0 2]
 [8 0 7]]
[[0 9 8]
 [3 0 0]
 [2 2 7]]


In [ ]:
# Czy transpozycja jest osobnym obiektem ?

In [64]:
print(np.linalg.inv(a))
print(np.linalg.det(a))

[[ 0.12 -0.04  0.12]
 [ 0.21  0.1  -0.29]
 [-0.23  0.08  0.1 ]]
156.0


In [70]:
print(np.unique(a))

[0 1 2 8 9]


In [78]:
x = np.array([[1,1],[2,2]])
print(x)

[[1 1]
 [2 2]]


In [82]:
#Funkcje mogą być wykorzystywane jako metody obiektu 'array' lub funkcje pakiety numpy
print() # sum
print() # min
print() # mean
print() # std
print() # median
print() # cumsum

()
()
()
()
()
()


## Parametr 'axis'

![fig3](http://scipy-lectures.org/_images/reductions.png)

In [75]:
x.sum(axis=1)

array([2, 4])

## Find index of the value

In [83]:
x.argmin()

0

In [100]:
idx = np.argwhere(x>1)

In [102]:
print(idx)

[[1 0]
 [1 1]]


## Logical operations

In [101]:
a = np.zeros((100,100))

print(np.any(a!=0))
print(np.all(a==0))

print((a != 0).any())
print((a == 0).all())

False
True
False
True


In [79]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

print(a,b,c)

# print(((a <= b) & (b <= c)).all())

(array([1, 2, 3, 2]), array([2, 2, 3, 2]), array([6, 4, 4, 5]))


## Broadcasting (przewidywanie)

![fig4](http://scipy-lectures.org/_images/numpy_broadcasting.png)

In [80]:
a = np.array([[ 0,  0,  0],[10,10,10],[20,20,20],[30,30,30]])
b = np.array([[ 0,  1,  2],[ 0,  1,  2],[ 0,  1,  2],[ 0,  1,  2]])
c = np.array([0,1,2]).reshape(1,-1)
d = np.array([0,10,20,30]).reshape(-1,1)
print(a)
print(b)
print(c)
print(d)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 1 2]]
[[ 0]
 [10]
 [20]
 [30]]


In [81]:
print(a+b)
print(a+c)
print(c+d)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


## Manipulacja rozmiarem macierzy

In [154]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [83]:
print(a)
print(a.ravel()) #spłaszczenie
print(a.ravel().reshape((2,3)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [103]:
a = np.arange(100)
a.shape = #
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [162]:
a = np.arange(100).reshape(10,-1)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


## Łączenie macierzy

In [104]:
a = np.array([[1, 2], [3, 4]])

In [105]:
b = np.repeat(a,3)
a,b,np.shape(a),np.shape(b)

(array([[1, 2],
        [3, 4]]),
 array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]),
 (2L, 2L),
 (12L,))

In [95]:
np.tile(a,3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [97]:
b = np.array([[5, 6]])

In [100]:
# concatenate
# hstack i vstack

## Iteracje po macierzach
UNIKAĆ ! MUSISZ MIEĆ DOBRY POWÓD !

In [132]:
b = np.arange(12).reshape(3,4)
for row in b:
    print row

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [145]:
for row in b:
    for element in row:
        element = 2**element
        print(element)

print(b)

2
4
16
256
65536
0
0
0
0
0
0
0
[[   1    2    4    8]
 [  16   32   64  128]
 [ 256  512 1024 2048]]


In [144]:
for (i,j), element in np.ndenumerate(b):
    b[i,j] = 2**element
print(b)

[[   1    2    4    8]
 [  16   32   64  128]
 [ 256  512 1024 2048]]


## Wczytywanie danych z pliku

In [147]:
# np.loadtxt() # Szybkie i ubogie w funkcje
# np.genfromtxt() # Wolniejsze za to pozwala na więcej

In [152]:
from StringIO import StringIO

data_str = '''0.0 0.0
1.0 1.0
2.0 2.0
3.0 3.0
4.0 4.0
2.3 1.1
1.2 3.5
3.1 0.2
'''

data = np.genfromtxt(StringIO(data_str))

### Przykład - wpasowanie funkcji liniowej w zbiór punktów metodą najmniejszych kwadratów
---

In [109]:
import numpy as np
from StringIO import StringIO

data = np.loadtxt('punkty.txt')

print data

size_data = len(data)

A = np.hstack((np.ones([size_data,1]),data[:,0].reshape(-1,1)))     

l = data[:,1]

print A.shape
print l.shape

x = np.dot(np.linalg.inv(np.dot(A.T,A)),np.dot(A.T,l))

print x

[[ 0.   0. ]
 [ 1.   1. ]
 [ 2.   2. ]
 [ 3.   3. ]
 [ 4.   4. ]
 [ 2.3  1.1]
 [ 1.2  3.5]
 [ 3.1  0.2]]
(8L, 2L)
(8L,)
[ 0.69  0.56]


## Inny przykład
http://hpiers.obspm.fr/eoppc/eop/eopc04/eopc04.19