In [1]:
import numpy as np

## Zadanie 1:
- Stwórz wektor w zakresie -1.3 do 2.5 posiadający równo rozmieszczone 64 elementy
- Stwórz wektor o rozmiarze 3n powtarzający ciąg [1,2,3]
- Stwórz wektor zaqwierający 10 kolejnych liczb nieparzystych

In [12]:
a = np.linspace(1.3,2.5,64)
print(a)
b = np.array([1,2,3])
c = np.tile(b,3)
print(c)

[ 1.3         1.31904762  1.33809524  1.35714286  1.37619048  1.3952381
  1.41428571  1.43333333  1.45238095  1.47142857  1.49047619  1.50952381
  1.52857143  1.54761905  1.56666667  1.58571429  1.6047619   1.62380952
  1.64285714  1.66190476  1.68095238  1.7         1.71904762  1.73809524
  1.75714286  1.77619048  1.7952381   1.81428571  1.83333333  1.85238095
  1.87142857  1.89047619  1.90952381  1.92857143  1.94761905  1.96666667
  1.98571429  2.0047619   2.02380952  2.04285714  2.06190476  2.08095238
  2.1         2.11904762  2.13809524  2.15714286  2.17619048  2.1952381
  2.21428571  2.23333333  2.25238095  2.27142857  2.29047619  2.30952381
  2.32857143  2.34761905  2.36666667  2.38571429  2.4047619   2.42380952
  2.44285714  2.46190476  2.48095238  2.5       ]
[1 2 3 1 2 3 1 2 3]


## Zadanie 2:
- Używając zadanych wektorów, wykorzystaj funkcję np.dot na kombinacjach wektorXwektor, wektorXmacierz, macierzXmacierz
- Sprawdz rozmiary otrzymanych macierzy


In [13]:
a=np.arange(4)
b=np.arange(16).reshape(4,4)

In [22]:
c=np.dot(a,a)
c,c.shape,type(c),c.ndim

(14, (), numpy.int32, 0)

In [24]:
c=np.dot(a,b)
c,c.shape,type(c),c.ndim

(array([56, 62, 68, 74]), (4L,), numpy.ndarray, 1)

In [23]:
c=np.dot(b,b)
c,c.shape,type(c),c.ndim

(array([[ 56,  62,  68,  74],
        [152, 174, 196, 218],
        [248, 286, 324, 362],
        [344, 398, 452, 506]]), (4L, 4L), numpy.ndarray, 2)

## Zadanie 3
- Oblicz sinusy i cosinusy dla 4 wartości w zakresie 0,2*pi
- zestaw wynik w postaci macierzy w której pierwszy wiersz to wartości, drugi sinusy, trzeci cosinusy

In [36]:
a = np.linspace(0,2*np.pi,4).reshape(1,-1)
b = np.sin(a).reshape(1,-1)
c = np.cos(a).reshape(1,-1)

d = np.concatenate((a,b,c))
d,d.shape,d.ndim


(array([[  0.00000000e+00,   2.09439510e+00,   4.18879020e+00,
           6.28318531e+00],
        [  0.00000000e+00,   8.66025404e-01,  -8.66025404e-01,
          -2.44929360e-16],
        [  1.00000000e+00,  -5.00000000e-01,  -5.00000000e-01,
           1.00000000e+00]]), (3L, 4L), 2)

## Zadanie 4
- Stwórz macierz liczb losowych o rozmiarze 3x5
- Oblicz sumę wszystkich wartości, sumę każdej kolumny, srednią każdego wiersza

In [39]:
e = np.random.random((3,5))
e.sum(),e.sum(axis=0),e.mean(axis=1)

(7.5401559370108986,
 array([ 1.07966636,  1.77972814,  1.31310669,  1.82120888,  1.54644587]),
 array([ 0.42406748,  0.70125449,  0.38270921]))

## Zadanie 5
- Oblicz ((A+B)*(-A/2)) nie stosując przypisania (D=A+B) << NIE

In [41]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
A,B,C

(array([ 1.,  1.,  1.]), array([ 2.,  2.,  2.]), array([ 3.,  3.,  3.]))

In [42]:
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
A

array([-1.5, -1.5, -1.5])

## Zadanie 6
- Stwórz macierz 5x5 każdy wiersz to liczby od 0 do 4

In [50]:
a = np.zeros((5,5))
a += np.arange(0,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [48]:
b = np.arange(0,5.0)
np.tile(b,5).reshape(5,-1)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

## Zadanie 7
- Stwórz losową macierz 10x2, reprezentującą współrzędne kartezjańskie x i y
- Zamień współrzędne kartezjańskie na biegunowe

In [51]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[ 0.9730845   0.39425625  0.59966026  0.62706563  0.45370044  0.62538872
  0.98341593  0.44917887  0.8340903   0.78068394]
[ 1.38284097  0.32620438  1.23943432  1.32072777  1.09883955  1.3901841
  1.22357088  0.63857878  0.54467329  0.94918047]


## Zadanie 8
- Stwórz losową macierz 5x10
- Odejmij od każdego wiersza wartość średnią dla tego wiersza


In [55]:
X = np.random.rand(5, 3)

Y = X - X.mean(axis=1).reshape(-1,1)

print(Y)

[[-0.34124438  0.4571318  -0.11588742]
 [-0.02758146 -0.14606361  0.17364507]
 [-0.14457593 -0.23372406  0.37829999]
 [-0.19793612 -0.18838619  0.38632231]
 [ 0.36548263 -0.41011654  0.04463391]]


## Zadanie 9
- Utwórz losową macierz 5x5 w zakresie liczb od 10 do 25
- Znajdź liczbę w macierzy która jest najblliższa liczby 15

In [93]:
Z = np.random.uniform(10,25,(5,5))
print Z
z = 16
idx=np.abs(Z - z).argmin()
print(Z.flat[idx],idx)

[[ 21.4038828   17.04532828  11.53281074  11.02797505  19.20948984]
 [ 24.01351093  21.81372596  15.85443913  11.54778699  23.99811131]
 [ 22.67617473  23.33190861  16.06668249  16.71824776  14.53682778]
 [ 22.93673522  11.58489722  11.68960242  15.95230428  20.51811351]
 [ 20.20020475  13.43503178  23.22431552  22.13978028  14.41759416]]
(15.952304278256005, 18)


In [100]:
idx=np.unravel_index(np.abs(Z - z).argmin(), a.shape)
print(idx)
print(Z[idx],idx)

(3, 3)
(15.952304278256005, (3, 3))


## Zadanie 10
- Stwórz dwie dowolne macierze 5x5
- Weź diagonalną iloczynu tych macierzy (2 sposoby)

Hint: Diagonalna to suma każdej kolumny powstałej z wymnożenia każdego elementu macierzy A z odpowiadającym elementem transpozycją macierzy B

In [108]:
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))

print(np.diag(np.dot(a,b)))
print(np.sum(a*b.T,axis=1))

[ 1.22118353  1.13889109  1.0781185   1.19470721  0.86761369]
[ 1.22118353  1.13889109  1.0781185   1.19470721  0.86761369]


## Zadanie 11
- Mając wektor [1,2,3,4,5] rozdziel każdą z liczb dwoma zerami. Wynik [1,0,0,2,0,0,3,....]

In [127]:
Z = np.array([1,2,3,4,5])

number_of_zeros = 2
Z0 = np.zeros(len(Z) + (len(Z)-1)*number_of_zeros)
print(Z0)
Z0[::number_of_zeros+1] = Z
print(Z0)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  0.  0.  2.  0.  0.  3.  0.  0.  4.  0.  0.  5.]


## Zadanie 12
- Stwórz macierz 5x5 zawierającą 25 kolejnych liczb (od 0 do 24)
- Zamień miejscami wiersz pierwszy z wierszem drugim

Hint: Weź wycinek zawierający pierwszy i drugi wiersz podmień go na wycinek zawierający drugi i pierwszy wiersz

In [129]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Zadanie 13
- Stwórz macierz losowych elementów o wymiarze 3x100 (uzyj funkcji random.normal(size=(3,100)))
- Oblicz średnią i odchylenie standardowe dla każdego wiersza
- Dla każdego wiersza, zamień wartości przekraczajace podwójne odchylenie standardowe od średniej na wartość np.nan (Not a number)

In [191]:
Z = np.random.normal(size=(3,100))

means = Z.mean(axis=1)
stds = Z.std(axis=1)

print(means,stds)

for i,row in enumerate(Z):
    x = np.argwhere((row<means[i]-2*stds[i])|(row>means[i]+2*stds[i])) #indexy wartości przekraczającyh zakres
    row[x]=np.nan
    Z[i]=row
    
print(Z)

(array([ 0.15717978, -0.00943171, -0.14547075]), array([ 0.99488987,  1.17885941,  1.04587554]))
[[ 1.35051494 -0.01754766  0.629379   -0.23249355 -1.23883401  0.81623711
   0.1157526   1.84400053  0.65621283  0.09706056  1.20527898  0.50702449
  -0.75996054 -0.49848112 -1.78990245 -0.36737415  0.61045811         nan
   0.09802065 -0.68563684  0.5503347  -1.52750305 -0.34649527  0.20311894
  -0.4154317  -0.70220651         nan  0.16486037  0.13978745         nan
  -1.18011171  0.28612451 -1.31513247  0.32481438  0.45780961  1.8065004
   1.4974827  -1.58879186  1.29280056  0.27035553 -0.75753222 -0.19543917
  -0.07674109 -0.13897471  0.89062121 -0.17947683 -0.27281753 -0.48547609
          nan  0.76953791  0.17414469  0.53899778 -0.3661615   1.51866884
   0.38525139  0.92377962  0.25292912 -0.19249354 -1.78519846 -0.38208563
  -0.62432711 -0.08559067  0.64977071 -0.21691119  0.35416959  0.81212468
   1.31635557 -1.17392047 -1.13355292 -0.63627242  0.13060563 -0.39453024
   0.98075137  0

## Zadanie 14
- Stwórz macierz 3x3 zawierającą wartości od 0 do 8 (włącznie)
- Odwróc kolejność wierszy
- Odwróć kolejność kolumn

In [197]:
a = np.arange(0,9).reshape(3,3)

b = a[::-1]
print(b)
c = a[:,::-1]
print(c)

[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
